#!/usr/bin/env python3
"""
Generate a JavaScript file that can be pasted into the Chrome browser console
on thrivethemes.com/wp-admin to upload screenshots and update ht-kb drafts.

The JS embeds screenshot images as base64, uploads them via WP REST API,
injects wp:image blocks into the original Gutenberg content, and updates
the existing draft posts.

Usage:
    python3 gen_chrome_publish.py [--article SLUG]

    Then paste the output JS file into Chrome DevTools console on thrivethemes.com/wp-admin.
"""
import base64
import json
import os
import re
import sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SCREENSHOTS_DIR = os.path.join(BASE_DIR, "screenshots")
WP_POSTS_JSON = os.path.join(BASE_DIR, "wp_posts.json")


def load_wp_posts():
    with open(WP_POSTS_JSON, "r", encoding="utf-8") as f:
        posts = json.load(f)
    return {p["filename"]: p for p in posts}


def load_manifest(article_slug):
    manifest_path = os.path.join(SCREENSHOTS_DIR, article_slug, "_manifest.json")
    if not os.path.exists(manifest_path):
        return None
    with open(manifest_path, "r") as f:
        return json.load(f)


def get_annotated_screenshots(manifest):
    return [s for s in manifest.get("screenshots", []) if s.get("found")]


def group_screenshots_by_section(screenshots):
    groups = {}
    for s in screenshots:
        section = s["section"]
        if section not in groups:
            groups[section] = []
        groups[section].append(s)
    return groups


def image_to_base64(filepath):
    with open(filepath, "rb") as f:
        return base64.b64encode(f.read()).decode("ascii")


def build_article_data(filename):
    """Build all data needed for one article."""
    article_slug = filename.replace(".md", "")
    wp_posts = load_wp_posts()

    if filename not in wp_posts:
        print(f"ERROR: {filename} not in wp_posts.json")
        return None

    original = wp_posts[filename]
    manifest = load_manifest(article_slug)
    if not manifest:
        print(f"No manifest for {article_slug}")
        return None

    annotated = get_annotated_screenshots(manifest)
    if not annotated:
        print(f"No annotated screenshots for {article_slug}")
        return None

    section_groups = group_screenshots_by_section(annotated)

    # Build image data with base64
    images = []
    seen = set()
    for s in annotated:
        if s["file"] in seen:
            continue
        seen.add(s["file"])

        abs_path = os.path.join(SCREENSHOTS_DIR, article_slug, s["file"])
        if not os.path.exists(abs_path):
            print(f"  WARNING: {abs_path} not found")
            continue

        b64 = image_to_base64(abs_path)
        images.append({
            "filename": s["file"],
            "b64": b64,
            "alt": f"{s['section']} - {s['target']} in Thrive Apprentice",
            "section": s["section"],
        })

    return {
        "filename": filename,
        "title": original["title"],
        "content": original["content"],
        "categories": original.get("categories", []),
        "section_groups": {
            section: [{"file": s["file"], "section": s["section"], "target": s["target"]} for s in screenshots]
            for section, screenshots in section_groups.items()
        },
        "images": images,
    }


def generate_js(articles_data):
    """Generate JavaScript that uploads images and updates posts."""

    # Serialize article data (without base64 — we'll handle that separately)
    articles_json = []
    all_images = []

    for ad in articles_data:
        # Keep images separate to manage the blob
        for img in ad["images"]:
            all_images.append({
                "article": ad["filename"],
                "filename": img["filename"],
                "b64": img["b64"],
                "alt": img["alt"],
            })

        articles_json.append({
            "filename": ad["filename"],
            "title": ad["title"],
            "content": ad["content"],
            "categories": ad["categories"],
            "section_groups": ad["section_groups"],
            "image_filenames": [img["filename"] for img in ad["images"]],
        })

    js = f"""
// =========================================================
// Screenshot Publisher for thrivethemes.com ht-kb drafts
// Generated by gen_chrome_publish.py
// Paste this into Chrome DevTools console on wp-admin
// =========================================================
(async function() {{
  const nonce = wpApiSettings.nonce;
  if (!nonce) {{ console.error('No WP nonce found!'); return; }}

  // Status overlay
  const statusEl = document.createElement('div');
  statusEl.style.cssText = 'position:fixed;top:10px;right:10px;background:#000;color:#0f0;padding:20px;z-index:999999;font-family:monospace;font-size:13px;max-height:80vh;overflow-y:auto;border-radius:8px;min-width:500px;max-width:600px;';
  document.body.appendChild(statusEl);
  function log(msg) {{
    statusEl.innerHTML += msg + '<br>';
    statusEl.scrollTop = statusEl.scrollHeight;
    console.log(msg);
  }}

  // --- Image data (base64-encoded PNGs) ---
  const imageData = {json.dumps(all_images, ensure_ascii=False)};

  // --- Article data ---
  const articles = {json.dumps(articles_json, ensure_ascii=False)};

  // Helper: convert base64 to File object
  function b64toFile(b64, filename) {{
    const byteString = atob(b64);
    const ab = new ArrayBuffer(byteString.length);
    const ia = new Uint8Array(ab);
    for (let i = 0; i < byteString.length; i++) {{
      ia[i] = byteString.charCodeAt(i);
    }}
    return new File([ab], filename, {{ type: 'image/png' }});
  }}

  // Helper: make Gutenberg image block
  function makeImageBlock(id, url, alt) {{
    return `<!-- wp:image {{"id":${{id}},"sizeSlug":"large"}} -->\\n<figure class="wp-block-image size-large"><img src="${{url}}" alt="${{alt}}" class="wp-image-${{id}}"/></figure>\\n<!-- /wp:image -->`;
  }}

  // Helper: inject images into content (same logic as Python version)
  function injectImages(content, sectionGroups, fileToMedia) {{
    for (const [sectionName, screenshots] of Object.entries(sectionGroups)) {{
      const imageBlocks = [];
      for (const s of screenshots) {{
        if (fileToMedia[s.file]) {{
          const m = fileToMedia[s.file];
          imageBlocks.push(makeImageBlock(m.id, m.url, m.alt));
        }}
      }}
      if (imageBlocks.length === 0) continue;

      const imagesHtml = imageBlocks.join('\\n\\n');

      // Find the section heading
      const escaped = sectionName.replace(/[.*+?^${{}}()|[\\]\\\\]/g, '\\\\$&');
      let headingRegex = new RegExp('<h[23]>' + escaped + '</h[23]>', 'i');
      let match = content.match(headingRegex);

      if (!match) {{
        // Try partial match with first and last words
        const words = sectionName.split(/\\s+/);
        if (words.length >= 2) {{
          const first = words[0].replace(/[.*+?^${{}}()|[\\]\\\\]/g, '\\\\$&');
          const last = words[words.length-1].replace(/[.*+?^${{}}()|[\\]\\\\]/g, '\\\\$&');
          headingRegex = new RegExp('<h[23]>[^<]*' + first + '[^<]*' + last + '[^<]*</h[23]>', 'i');
          match = content.match(headingRegex);
        }}
      }}

      if (!match) {{
        log('  WARNING: heading not found: ' + sectionName);
        continue;
      }}

      // Find <!-- /wp:list --> after the heading
      const headingEnd = match.index + match[0].length;
      const afterHeading = content.substring(headingEnd);
      const listCloseIdx = afterHeading.indexOf('<!-- /wp:list -->');

      if (listCloseIdx === -1) {{
        log('  WARNING: no list after heading: ' + sectionName);
        continue;
      }}

      const insertPos = headingEnd + listCloseIdx + '<!-- /wp:list -->'.length;
      content = content.substring(0, insertPos) + '\\n\\n' + imagesHtml + content.substring(insertPos);
    }}
    return content;
  }}

  // ========== MAIN PROCESS ==========
  log('<b>Starting screenshot publish...</b>');

  // Step 1: Upload all images
  log('<br><b>Step 1: Uploading screenshots to media library...</b>');
  const fileToMedia = {{}};

  for (let i = 0; i < imageData.length; i++) {{
    const img = imageData[i];
    if (fileToMedia[img.filename]) continue;

    log('  Uploading ' + (i+1) + '/' + imageData.length + ': ' + img.filename);

    try {{
      const file = b64toFile(img.b64, img.filename);
      const formData = new FormData();
      formData.append('file', file);

      const resp = await fetch('/wp-json/wp/v2/media', {{
        method: 'POST',
        headers: {{ 'X-WP-Nonce': nonce }},
        body: formData
      }});

      if (!resp.ok) {{
        const errText = await resp.text();
        log('    <span style="color:red">ERROR: ' + resp.status + ' - ' + errText.substring(0, 100) + '</span>');
        continue;
      }}

      const media = await resp.json();
      fileToMedia[img.filename] = {{
        id: media.id,
        url: media.source_url,
        alt: img.alt
      }};

      // Set alt text
      await fetch('/wp-json/wp/v2/media/' + media.id, {{
        method: 'POST',
        headers: {{ 'Content-Type': 'application/json', 'X-WP-Nonce': nonce }},
        body: JSON.stringify({{ alt_text: img.alt }})
      }});

      log('    -> ID: ' + media.id + ' (' + media.source_url.split('/').pop() + ')');
    }} catch (e) {{
      log('    <span style="color:red">ERROR: ' + e.message + '</span>');
    }}

    // Small delay between uploads
    await new Promise(r => setTimeout(r, 300));
  }}

  log('<br>Uploaded ' + Object.keys(fileToMedia).length + '/' + imageData.length + ' images');

  // Step 2: Process each article
  for (const article of articles) {{
    log('<br><b>Processing: ' + article.filename + '</b>');
    log('  Title: ' + article.title);

    // Find the existing draft
    log('  Searching for existing draft...');
    let postId = null;

    for (const status of ['draft', 'publish', 'any']) {{
      try {{
        const resp = await fetch('/wp-json/wp/v2/ht-kb?search=' + encodeURIComponent(article.title) + '&status=' + status + '&per_page=10', {{
          headers: {{ 'X-WP-Nonce': nonce }}
        }});
        if (resp.ok) {{
          const posts = await resp.json();
          for (const post of posts) {{
            if (post.title.rendered.trim() === article.title.trim()) {{
              postId = post.id;
              break;
            }}
          }}
        }}
      }} catch (e) {{}}
      if (postId) break;
    }}

    if (!postId) {{
      log('  <span style="color:yellow">Draft not found! Skipping.</span>');
      continue;
    }}

    log('  Found draft: ID=' + postId);

    // Inject images into original content
    const newContent = injectImages(article.content, article.section_groups, fileToMedia);
    const addedChars = newContent.length - article.content.length;
    log('  Content: ' + article.content.length + ' -> ' + newContent.length + ' chars (+' + addedChars + ')');

    // Update the post
    log('  Updating post...');
    try {{
      const resp = await fetch('/wp-json/wp/v2/ht-kb/' + postId, {{
        method: 'POST',
        headers: {{ 'Content-Type': 'application/json', 'X-WP-Nonce': nonce }},
        body: JSON.stringify({{ content: newContent }})
      }});

      if (resp.ok) {{
        const updated = await resp.json();
        log('  <span style="color:#0f0">✓ Updated successfully!</span>');
        log('  Edit: <a href="/wp-admin/post.php?post=' + postId + '&action=edit" style="color:cyan">/wp-admin/post.php?post=' + postId + '&action=edit</a>');
      }} else {{
        const errText = await resp.text();
        log('  <span style="color:red">ERROR updating: ' + resp.status + ' - ' + errText.substring(0, 200) + '</span>');
      }}
    }} catch (e) {{
      log('  <span style="color:red">ERROR: ' + e.message + '</span>');
    }}
  }}

  log('<br><b style="color:#0f0">===== DONE =====</b>');

  // Store results globally
  window.__publishResults = {{ fileToMedia, articles: articles.map(a => a.filename) }};
}})();
"""
    return js


def main():
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--article", help="Specific article slug")
    parser.add_argument("--all", action="store_true", help="All articles with manifests")
    args = parser.parse_args()

    filenames = []
    if args.article:
        fn = args.article
        if not fn.endswith(".md"):
            fn += ".md"
        filenames = [fn]
    elif args.all:
        for d in sorted(os.listdir(SCREENSHOTS_DIR)):
            manifest_path = os.path.join(SCREENSHOTS_DIR, d, "_manifest.json")
            if os.path.exists(manifest_path):
                filenames.append(d + ".md")
    else:
        filenames = [
            "1-01-creating-your-first-course.md",
            "2-01-settings-guide.md",
        ]

    print(f"Building data for {len(filenames)} articles...")
    articles_data = []
    for fn in filenames:
        print(f"  {fn}...")
        data = build_article_data(fn)
        if data:
            total_b64_size = sum(len(img["b64"]) for img in data["images"])
            print(f"    {len(data['images'])} images, ~{total_b64_size // 1024}KB base64")
            articles_data.append(data)

    if not articles_data:
        print("No articles to process!")
        return

    js = generate_js(articles_data)

    output_path = os.path.join(BASE_DIR, "publish_screenshots.js")
    with open(output_path, "w") as f:
        f.write(js)

    size_kb = os.path.getsize(output_path) / 1024
    print(f"\nGenerated: {output_path}")
    print(f"Size: {size_kb:.0f} KB")
    print(f"\nTo use: Copy the contents of publish_screenshots.js and paste into")
    print(f"Chrome DevTools console on https://thrivethemes.com/wp-admin/")


if __name__ == "__main__":
    main()
